In [55]:
import numpy as np

#Create a list and print
my_list = [1,2,3]
my_list

[1, 2, 3]

In [56]:
#Convert list to array and print
x = np.array(my_list)
x

array([1, 2, 3])

In [57]:
#Check the object type of x
type(x)

numpy.ndarray

In [58]:
#Convert a matrix to array
my_matrix = [1,2,3],[4,5,6],[7,8,9]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
#NP version of range
#Start with 1 till 11 at steps of 2
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [60]:
#Start with 0 till 11 at steps of 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [61]:
#One dimension array of zeros
np.zeros(4)

array([0., 0., 0., 0.])

In [62]:
#Two dimension array of zeros
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
#One dimension array of ones
np.ones(3)

array([1., 1., 1.])

In [64]:
#Two dimension array of ones
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [65]:
#Evenly spaced values between a specific range
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [66]:
#Generate a square matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
#Generate a randpm matrix with normal distribution
np.random.rand(5,4)

array([[0.26785983, 0.89366272, 0.97334068, 0.09379287],
       [0.25236783, 0.45031525, 0.745031  , 0.03881223],
       [0.7757571 , 0.26369159, 0.99807602, 0.42988519],
       [0.09936046, 0.84662906, 0.27701605, 0.50004309],
       [0.24986291, 0.56587511, 0.18909189, 0.25625053]])

In [68]:
#Generate a random matrix with standard normal distribution (bell curve)
np.random.randn(5,4)

array([[ 0.05974573, -1.0892439 ,  1.05433363, -0.81884908],
       [-0.39433564,  0.84790185, -1.78874207, -1.4362597 ],
       [-1.66903081,  0.91031188,  0.147268  , -1.355537  ],
       [-0.69795373, -2.73630538,  0.69329739,  1.4106579 ],
       [ 0.33717236,  1.54910421,  0.287412  ,  0.50776816]])

In [69]:
#Randomly generate a number between 0 to 2
np.random.randint(3)

2

In [71]:
Create a variable arr with a range form 0 to 24
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [73]:
#Create a variable with 10 random values between 0 to 49 
ranarr = np.random.randint(0,50,10)
ranarr

array([30, 16, 48, 21,  4, 17, 38, 24, 47, 29])

In [74]:
#Reshape variable arr into a 5 by 5 matrix
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
#Check the shape
arr.shape

(25,)

In [76]:
#Check the shape after reshape
arr.reshape(5,5).shape

(5, 5)

In [77]:
#Ask for the data type
arr.dtype

dtype('int32')

In [80]:
#Display the max value
ranarr.max()

48

In [81]:
#Display the index of the max value
ranarr.argmax()

2

In [82]:
#Display the min value
ranarr.min()

4

In [83]:
#Display the index of the min value
ranarr.argmin()

4